import './globals.css'
import { Jost } from 'next/font/google'
// setting font family
const inter = Jost({  subsets: ['latin'] })
// metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
