import "./globals.css";
import Navbar from "@/components/layout/navbar";
import AuthProvider from "./context/AuthProvider";
import { Jost } from "next/font/google";
import Footer from "@/components/layout/footer";
// setting font family
const inter = Jost({ subsets: ["latin"] });
// metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
