import "./globals.css";
import Navbar from "@/components/layout/navbar";
import AuthProvider from "./context/AuthProvider";
import { Jost } from "next/font/google";
import Footer from "@/components/layout/footer";
import QueryProvider from "./context/QueryProvider";
// setting font family
const inter = Jost({ subsets: ["latin"] });
// metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
